const FRAMES_PER_SECOND = 60;
const MILLISECONDS_PER_SECOND = 1000;

const NUM_POINTS = 30;
const MAX_POINT_SPEED = 0.5;

const LINE_COLOR = "#ffffff";
const POINT_COLOR = "#ffffff";

const BACKGROUND_COLOR_1 = "#1f145c";
const BACKGROUND_COLOR_2 = "#000000";

const POINT_RADIUS = 3;
const LINE_WIDTH_MULTIPLIER = 500;
const LINE_WIDTH_EXPONENT = 1.6;

const MAX_LINE_WIDTH = 3;
const MIN_LINE_WIDTH = 0.15;

export {
  FRAMES_PER_SECOND,
  MILLISECONDS_PER_SECOND,
  NUM_POINTS,
  MAX_POINT_SPEED,
  LINE_COLOR,
  POINT_COLOR,
  BACKGROUND_COLOR_1,
  BACKGROUND_COLOR_2,
  POINT_RADIUS,
  LINE_WIDTH_MULTIPLIER,
  LINE_WIDTH_EXPONENT,
  MAX_LINE_WIDTH,
  MIN_LINE_WIDTH,
};
